### ISSUE TITLE
logger debug and info in iterate functiond don't actually print the message

### ISSUE THREAD

**Issue by limor-gs** [cloudify-cosmo/repex#39] opened 2016-09-13 13:25 UTC

**Comment by limor-gs** [comment] 2016-09-13 13:44
It seems that the function replace the strings correctly.

**Comment by nir0s** [comment] 2017-01-12 13:59
I could not reproduce this. Please reproduce and send the logs

**Comment by nir0s** [comment] 2017-01-18 11:43
Verbosity configuration has changed in v1.1.0. I'm closing this for now.

**Closed by nir0s** 2017-01-18 11:43 UTC
